name: Docker Image CI

on:
  push:
    branches: [ "feature" ]
  pull_request:

jobs:
  build-and-test-in-docker:
    runs-on: ubuntu-22.04
    container: ghcr.io/nrfconnect/sdk-nrf-toolchain:v2.6.99
    defaults:
      run:
        # Bash shell is needed to set toolchain related environment variables in docker container
        # It is a workaround for GitHub Actions limitation https://github.com/actions/runner/issues/1964
        shell: bash
    steps:
      - name: Checkout repository with example application
        uses: actions/checkout@v4
        with:
          path: example-application
      - name: Build firmware
        working-directory: example-application
        run: |
          cd example-application
          west build --build-dir example-application/build_1 example-application --pristine --board wp_rev1 --no-sysbuild -- -DNCS_TOOLCHAIN_VERSION=NONE -DBOARD_ROOT=example-application -DCACHED_CONF_FILE=example-application/prj.conf
      - name: Store hex files
        uses: actions/upload-artifact@v4
        with:
          name: built-applications
          path: example-application/twister-out/**/zephyr/zephyr.hex
