name: Docker Image CI

on:
  push:
    branches: [ "feature" ]
  pull_request:

jobs:
  build-wepower-project:
    runs-on: ubuntu-22.04
    container: ghcr.io/nrfconnect/sdk-nrf-toolchain:v2.6.99
    defaults:
      run:
        # Bash shell is needed to set toolchain related environment variables in docker container
        # It is a workaround for GitHub Actions limitation https://github.com/actions/runner/issues/1964
        shell: bash
    steps:
      - name: Checkout repository with BLE Beacon application
        uses: actions/checkout@v4
        with:
          path: WePower_BLE_Beacon
      - name: Prepare west project       
        run: |
          export PATH=$PATH:${HOME}/.local/bin
          west init -l WePower_BLE_Beacon
          west update -o=--depth=1 -n
          apt-get -y update
          apt-get -y install build-essential
      - name: Build firmware
        run: |
          cd WePower_BLE_Beacon
          west build --build-dir build . --pristine -DBOARD_ROOT=. -DNCS_TOOLCHAIN_VERSION=NONE  -DCACHED_CONF_FILE=prj.conf --board wp_rev1
      - name: Store hex files
        uses: actions/upload-artifact@v4
        with:
          name: built-applications
          path: WePower_BLE_Beacon/build/zephyr/WePower_BLE_BEACON.hex
